### ISSUE TITLE
Support for `lengths` argument

### ISSUE THREAD

**Issue by philgzl** [mpariente/pytorch_stoi#10]
Would you be interested in adding support for a `lengths` argument that contains the original lengths of the waveforms before batching? The user might be padding waveforms to match the length and create the batch, but this can change the results. If `use_vad=True` and the user is padding with zeros, the difference is small but not zero due to the last frame overlapping with padded zeros.

**Comment by mpariente** [comment]
As it is a loss, and not a metric, I don't find it very necessary, but if you need it for your use case, we can integrate it.

**Comment by philgzl** [comment]
Will think about it and see if I open a PR, closing this.
