### ISSUE TITLE
the range of pytorch_stoi's results

### ISSUE THREAD

**Issue by ChangLee0903** [mpariente/pytorch_stoi#2]
Hi Pariente, 

thanks for sharing such convenient tool, I have some questions about your testing results. I just guess that you modified the different SNR level to observe the different sample points. If SNR become large, the value of pystoi will approximate to 1.

Basing on the formula of original paper:
![image](https://user-images.githubusercontent.com/68819118/89058607-281e9400-d392-11ea-8eec-d65c0387ca2c.png)
I think the range of the result in ideal stoi is in [-1, 1].

However, in your result(which is in 16KHz with VAD) shows that the value of pytorch version can be higher than 1.
![image](https://user-images.githubusercontent.com/68819118/89058781-89466780-d392-11ea-9547-a54eebf5e82b.png)

Could you please provide more detailed information about how you test?

Best,
Chi-Chang Lee.

**Comment by ChangLee0903** [comment]
Sorry I just noted that you have mentioned this in the comment of stoi.py

**Comment by shamoons** [comment]
Can you please link to where in the file this is clarified?
