### ISSUE TITLE
CuBLAS error when OBM is not on GPU in PyTorch nightly

### ISSUE THREAD

**Issue by jonashaag** [mpariente/pytorch_stoi#4]
I use PyTorch nightly for their STFT implementation. pytorch_stoi crashes with

```pytb
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

at the OBM matrix multiplication:

```py
x_tob = torch.matmul(self.OBM, torch.norm(x_spec, 2, -1) ** 2).pow(0.5)
```

Moving `self.OBM` to the GPU first fixes the issue:

```py
self.OBM = nn.Parameter(torch.from_numpy(obm_mat).float(),
                        requires_grad=False).cuda()  # <==
```

Do you think that's a bug in PyTorch nightly?

My version:

```pycon
>>> torch.__version__
'1.7.0.dev20200818'
>>> torch.version.cuda
'10.2'
>>>
KeyboardInterrupt
>>> torch.version.git_version
'14b1e2392c2b91aea922a33b916cee5cf079c5b8'
```

**Comment by mpariente** [comment]
> Moving self.OBM to the GPU first ...

But did you move the loss instance to cuda before calling it?

**Comment by jonashaag** [comment]
Oh, I did not. Interestingly, it worked with PyTorch 1.6 without moving the loss to GPU.

**Comment by mpariente** [comment]
That's pretty weird ^^

**Comment by mpariente** [comment]
I'll close!
